{
  "hash": "e6d60f87e8d1059c8a7ed27c14232f2e",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Automation Paradox: Who Really Gets Hurt When AI Takes Over?\"\nsubtitle: \"MIS502 Final Project — AI's Impact on the Job Market\"\nauthor: \"Taya Yakovenko\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: cosmo\n    code-fold: true\n    fig-width: 9\n    fig-height: 5\n  pdf:\n    toc: true\n    fig-width: 7\n    fig-height: 4\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n\n## Executive Summary\n\nArtificial intelligence is transforming the US labor market — but not in the simple\n\"robots taking all jobs\" narrative that dominates headlines. Using three authoritative\nreal-world datasets — Frey & Osborne's automation probability scores (2013), the Bureau\nof Labor Statistics' 2024–2034 employment projections, and the ILO's 2025 Generative AI\nOccupational Exposure Index — this report finds a more nuanced and more troubling pattern.\n\nThe **Automation Paradox**: most workers exposed to AI are currently seeing stable or\ngrowing employment. Yet hidden inside that aggregate is a concentrated crisis. Roughly\n**144** occupations (24% of analyzed jobs)\ncombine high automation risk with low wages and low education — leaving workers\nwith no economic safety net. These are the jobs where displacement is not a future\nconcern but a present reality.\n\n**Key findings:**\n\n- **283** of 606 matched occupations carry high (>70%)\n  automation risk — primarily in Office & Admin Support, Production, and Food Preparation\n- High-risk occupations have a median wage of **$48\\,350** —\n  compared to **$79\\,000** for low-risk occupations\n- A linear regression confirms automation risk negatively predicts employment growth\n  (coefficient: −4.15), but R² = 0.175 — meaning automation alone explains only 17.5%\n  of the variation in job outcomes\n- The most important protective factor is **education + wage combined** (adaptive\n  capacity score), not automation risk alone\n- A \"Then vs. Now\" comparison using the ILO 2025 GenAI Exposure Index reveals the\n  risk map has fundamentally shifted: **Computer & Math** reversed from low traditional\n  risk (13%) to highest GenAI exposure (56%), while **Production and Construction** —\n  flagged as near-certain automation targets in 2013 — score among the lowest on GenAI\n  exposure today. The workers we thought were safe may not be; the workers we feared\n  for may be safer than expected from GenAI specifically.\n\n---\n\n## 1. Introduction\n\nThe question \"Is AI taking our jobs?\" has a frustrating honest answer: *it depends on\nwhich jobs you're watching.* Aggregate employment statistics look healthy. But averages\nhide the distribution — and in labor economics, the distribution is everything.\n\nThis report investigates the structure of that distribution: which occupations are\ngenuinely at risk, what makes some workers resilient and others vulnerable, and what\nthe data says about where the US labor market is heading through 2034.\n\n### Research Questions\n\n1. Which occupations face the highest automation risk, and are those the same\n   occupations projected to decline?\n2. Does automation risk alone predict employment change, or do other factors matter more?\n3. Can we identify a \"vulnerability cluster\" — occupations combining high automation\n   exposure with low adaptive capacity?\n\n---\n\n## 2. Data Sources\n\n**A note on the original dataset:** This project was initially scoped around the\n*AI Impact on Job Market* dataset on Kaggle. Preliminary analysis showed near-zero\ncorrelations between all variables (r ≈ 0.001–0.012 across every pair), which is a\nhallmark of randomly generated synthetic data — there is no real signal to analyze.\nThat dataset was set aside in favor of the three authoritative real-world sources\ndescribed below.\n\nThree datasets are combined for this analysis:\n\n| Dataset | Source | Coverage | Role |\n|---|---|---|---|\n| Automation Probability Scores | Frey & Osborne (2013), *The Future of Employment* | 702 US occupations | Traditional automation baseline (\"then\") |\n| Employment Projections 2024–2034 | US Bureau of Labor Statistics | 832 occupations | Employment outlook |\n| GenAI Occupational Exposure Index | Gmyrek et al. (2025), ILO Working Paper 140 | 427 ISCO-08 occupations | GenAI exposure (\"now\") |\n| **Analysis dataset** | Inner join F&O × BLS; left join ILO via crosswalk | | **606 occupations, 99% with GenAI scores** |\n\nFrey & Osborne and BLS are joined on SOC codes (86% match rate). The ILO dataset uses\nISCO-08 codes and is bridged via the BLS official ISCO-08 × SOC crosswalk, covering\n600 of 606 occupations.\n\n\n---\n\n## 3. Automation Risk Distribution\n\n::: {#90753337 .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](report_files/figure-html/cell-3-output-1.png){width=652 height=364}\n:::\n:::\n\n\nThe distribution is notably bimodal: most occupations cluster at the extremes (very\nhigh or very low risk) rather than the middle. This reflects the nature of work tasks —\nthey tend to be either primarily routine (highly automatable) or primarily non-routine\n(resistant to automation), with fewer genuinely ambiguous cases.\n\n**By occupation group**, the highest-risk sectors are Office & Administrative Support\n(84% average probability), Production (82%), Farming & Fishing (78%), and Building &\nGrounds (78%). The safest sectors are Community & Social Service (5%), Healthcare\nPractitioners (12%), Computer & Math (13%), and Management (14%).\n\n::: {#ec6bb2f4 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](report_files/figure-html/cell-4-output-1.png){width=941 height=556}\n:::\n:::\n\n\n---\n\n## 4. The Core Relationship: Automation Risk vs. Job Growth\n\n::: {#24d4163a .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](report_files/figure-html/cell-5-output-1.png){width=844 height=460}\n:::\n:::\n\n\nThe scatter plot reveals the Automation Paradox visually. There is a clear negative\ntrend — occupations with higher automation probability cluster toward the lower portion\nof the chart. But the relationship is wide and noisy. Many high-automation occupations\nstill show positive projected employment growth. Automation risk is *predictive* but\nnot *deterministic*.\n\n**Correlation:** r = −0.414 between `automation_prob` and `emp_change_pct`. Moderate\nnegative relationship. **Linear regression R² = 0.175** — automation risk alone\nexplains only 17.5% of variance in employment change, even after adding wage, education,\nand occupation group controls.\n\n---\n\n## 5. Who Is Most At Risk?\n\n::: {#a19d70fa .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](report_files/figure-html/cell-6-output-1.png){width=856 height=460}\n:::\n:::\n\n\nThe most at-risk occupations combine near-certain automation probability (>95%) with\ndeclining employment projections: data entry keyers, word processors, insurance\nunderwriters, credit authorizers, and watch repairers. These are not hypothetical\nfuture risks — BLS projects active job losses in all of them through 2034.\n\n---\n\n## 6. Who Is Safe?\n\n::: {#475552b7 .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](report_files/figure-html/cell-7-output-1.png){width=955 height=460}\n:::\n:::\n\n\nThe safest and fastest-growing occupations are concentrated in healthcare (nurse\npractitioners, physician assistants, home health aides) and technology (software\ndevelopers, data scientists). These roles share common features: they require\ncomplex human judgment, physical dexterity in variable environments, deep domain\nexpertise, or meaningful human interaction — all barriers to automation.\n\n---\n\n## 7. The Economic Divide\n\n::: {#fbbdda1b .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![](report_files/figure-html/cell-8-output-1.png){width=1157 height=365}\n:::\n:::\n\n\nThe wage data tells a stark story. High-risk occupations have a median annual wage of\n**$48\\,350**, compared to **$79\\,000**\nfor low-risk occupations — a **$30\\,650** gap.\n\nThe box plot makes the distributional difference even clearer. Vulnerable occupations\n(high automation + low adaptive capacity) have a tightly compressed wage range centered\nat **$40\\,260**. Non-vulnerable occupations have a median of\n**$63\\,280** with a wide spread extending into six figures.\nThe workers most threatened by AI are also the least able to afford the retraining,\nrelocation, or career transition that adaptation requires.\n\n---\n\n## 8. Cluster Analysis: Three Paths Forward\n\nK-Means clustering (k=4, effectively 3 distinct segments) reveals three occupational\ntrajectories:\n\n::: {#775d0e92 .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![](report_files/figure-html/cell-9-output-1.png){width=928 height=365}\n:::\n:::\n\n\n| Cluster | Size | Avg Automation Prob | Avg Adaptive Capacity | Avg Wage | Projected Growth |\n|---|---|---|---|---|---|\n| **High Risk / Low Resilience** | 305 (50%) | 85.1% | 0.113 | $49,287 | −1.75% |\n| **Low Risk / Stable** | 225 (37%) | 27.1% | 0.155 | $66,965 | +2.58% |\n| **Low Risk / High Skill** | 70 (12%) | 9.0% | 0.625 | $126,322 | +5.51% |\n\nThe \"High Risk / Low Resilience\" cluster — 50% of matched occupations — faces declining\nemployment with virtually no adaptive buffer. The \"Low Risk / High Skill\" cluster —\nonly 12% of occupations — enjoys near-zero automation risk, strong job growth, and\nwages 2.5× higher than the at-risk group.\n\n---\n\n## 9. Then vs. Now: The GenAI Risk Shift (2013 → 2025)\n\n\n\nThe Frey & Osborne (2013) scores that underpin this report were groundbreaking for\ntheir era, but they measured a specific form of AI risk: algorithmic and robotic\nautomation of routine tasks. A decade later, Generative AI — large language models,\nmultimodal systems, code generation — presents a different kind of risk that targets\na different kind of work. The ILO's 2025 Generative AI Occupational Exposure Index\n(Gmyrek et al., ILO Working Paper 140) provides the most rigorous current estimate\nof that new risk, scored from 29,753 tasks across 427 ISCO-08 occupations.\n\n**Why this comparison matters:** If the risk landscape has shifted, then policies and\ncareer advice built on 2013 assumptions may be protecting the wrong people and exposing\nthe wrong sectors.\n\n### The Sector-Level Flip\n\n::: {#e3e1f153 .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![](report_files/figure-html/cell-11-output-1.png){width=967 height=748}\n:::\n:::\n\n\nThe dumbbell chart above tells the story clearly. Every sector with a connector line\npointing **left** (from blue to red dot) saw its risk *fall* moving from 2013 to 2025\n— these are physical sectors where GenAI has no mechanism for displacement. Every sector\nwith a line pointing **right** saw its risk *rise* — these are knowledge and information\nsectors that GenAI targets directly.\n\n**The largest reversals:**\n\n| Sector | 2013 Risk | 2025 GenAI Exposure | Δ |\n|---|---|---|---|\n| Computer & Math | 13% | 56% | **+43 pp** |\n| Community & Social Service | 5% | 28% | **+23 pp** |\n| Management | 14% | 37% | **+22 pp** |\n| Arts & Media | 21% | 37% | **+16 pp** |\n| Production | 82% | 20% | **−62 pp** |\n| Building & Grounds | 78% | 15% | **−62 pp** |\n| Construction | 74% | 13% | **−61 pp** |\n\n### The Occupation-Level Picture\n\n::: {#10a3810d .cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![](report_files/figure-html/cell-12-output-1.png){width=844 height=460}\n:::\n:::\n\n\nThe scatter plot places every occupation against a diagonal reference line. Points\n**above** the diagonal were underestimated by 2013 models — they face more GenAI\nexposure than traditional automation suggested. Points **below** were overestimated\n— high traditional automation risk that GenAI does not replicate.\n\n**The five most newly exposed occupations** (largest positive delta):\n\n::: {#4aa6b4ac .cell execution_count=12}\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Occupation</th>\n      <th>Sector</th>\n      <th>Traditional Risk (2013)</th>\n      <th>GenAI Exposure (2025)</th>\n      <th>Δ</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Credit counselors</td>\n      <td>Business &amp; Financial</td>\n      <td>4%</td>\n      <td>60%</td>\n      <td>+0.56</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Operations research analysts</td>\n      <td>Computer &amp; Math</td>\n      <td>4%</td>\n      <td>56%</td>\n      <td>+0.53</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Securities, commodities, and financial s...</td>\n      <td>Sales</td>\n      <td>2%</td>\n      <td>54%</td>\n      <td>+0.52</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Mathematicians</td>\n      <td>Computer &amp; Math</td>\n      <td>5%</td>\n      <td>56%</td>\n      <td>+0.51</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Writers and authors</td>\n      <td>Arts &amp; Media</td>\n      <td>4%</td>\n      <td>55%</td>\n      <td>+0.51</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n**The five most de-risked occupations** (largest negative delta):\n\n::: {#57a88f24 .cell execution_count=13}\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Occupation</th>\n      <th>Sector</th>\n      <th>Traditional Risk (2013)</th>\n      <th>GenAI Exposure (2025)</th>\n      <th>Δ</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Sewers, hand</td>\n      <td>Production</td>\n      <td>99%</td>\n      <td>12%</td>\n      <td>-0.87</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Log graders and scalers</td>\n      <td>Farming &amp; Fishing</td>\n      <td>97%</td>\n      <td>12%</td>\n      <td>-0.85</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Helpers--painters, paperhangers, plaster...</td>\n      <td>Construction &amp; Extraction</td>\n      <td>94%</td>\n      <td>9%</td>\n      <td>-0.85</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Pesticide handlers, sprayers, and applic...</td>\n      <td>Building &amp; Grounds</td>\n      <td>97%</td>\n      <td>13%</td>\n      <td>-0.84</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Cement masons and concrete finishers</td>\n      <td>Construction &amp; Extraction</td>\n      <td>94%</td>\n      <td>10%</td>\n      <td>-0.84</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### What This Means\n\nThe 2013 automation literature and the 2025 GenAI exposure data agree on one thing:\n**Office & Administrative Support is highly exposed** (84% traditional, 52% GenAI).\nClerical workers face sustained risk across both eras. But the agreement ends there.\n\nGenAI differs from robotic automation in a fundamental way: **it targets language,\nreasoning, and information synthesis** — not physical manipulation. This is why writers,\nanalysts, counselors, and mathematicians appear in the newly-exposed list, while\nbrickmasons, sewers, and groundskeepers appear in the de-risked list. The physical\ndexterity barrier that protected manual workers from robotics also protects them from\nGenAI.\n\nThe policy implication is significant: **retraining programs designed around the 2013\nrisk map may be solving the wrong problem.** A displaced office worker retrained for\na knowledge-intensive analytical role may be walking into the highest-GenAI-exposure\nsector. Healthcare and skilled trades — identified as safe harbors in the 2013 analysis\n— remain strong options under the 2025 lens.\n\n---\n\n## 10. Conclusions and Policy Implications\n\n**The Automation Paradox is real.** Automation risk and employment decline are related\n(r = −0.414) but not synonymous. Many high-automation occupations still show positive\ngrowth projections — the paradox reflects that AI raises productivity and creates new\nroles even as it displaces specific tasks.\n\n**But the paradox masks a concentrated crisis.** 144 occupations (23.8%) combine\nhigh automation exposure with wages and education too low to support adaptation.\nThese workers are not benefiting from the productivity windfall of AI. They are\nabsorbing the displacement costs with no safety net.\n\n**Three policy implications:**\n1. **Targeted retraining, not general retraining.** The vulnerable population is\n   identifiable by occupation — Office & Admin Support, Production, Food Preparation.\n   Broadly available training programs miss the specific workers at risk.\n2. **Wage floors matter as much as education.** Adaptive capacity depends on both.\n   Low-wage workers cannot access training, relocation, or extended job search even\n   with higher education.\n3. **Healthcare investment is a hedge.** The fastest-growing, safest occupations are\n   concentrated in healthcare — a sector driven by demographics, not AI adoption. Policies\n   that reduce barriers to healthcare careers (licensing, cost, geographic access) are\n   simultaneously labor market policies.\n\n**Limitations:** Frey & Osborne's scores date to 2013 and reflect a pre-GenAI understanding\nof automation risk — which is why this report includes the ILO 2025 comparison in Section 9.\nEven so, the ILO scores are global (ISCO-08) and were validated using Polish worker surveys;\nUS-specific GenAI adoption rates may differ. BLS projections are point estimates with\nunquantified uncertainty. The merged dataset covers 606 of 832 BLS-tracked occupations; 6\noccupations have no ISCO-08 equivalent and are excluded from the then/now analysis only.\n\n---\n\n## References\n\n- Frey, C.B. & Osborne, M.A. (2013). *The Future of Employment: How Susceptible Are\n  Jobs to Computerisation?* Oxford Martin School Working Paper.\n- U.S. Bureau of Labor Statistics (2024). *Employment Projections 2024–2034.*\n  U.S. Department of Labor. https://www.bls.gov/emp/\n- Gmyrek, P., Berg, J., & Bescond, D. (2025). *Generative AI and Jobs: A Refined\n  Global Index of Occupational Exposure.* ILO Working Paper 140. International Labour\n  Organization. https://www.ilo.org/publications/generative-ai-and-jobs-refined-global-index-occupational-exposure\n- Acemoglu, D. & Restrepo, P. (2018). Artificial Intelligence, Automation, and Work.\n  *NBER Working Paper 24196.*\n- Broady, K., McGrew, C., & Ouyang, A. (2024). *Measuring US Workers' Capacity to\n  Adapt to AI-Driven Job Displacement.* The Brookings Institution.\n\n",
    "supporting": [
      "report_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}