<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Taya Yakovenko">
<meta name="dcterms.date" content="2026-04-21">

<title>The Automation Paradox: Who Really Gets Hurt When AI Takes Over? – The Automation Paradox</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-200b7f763972437cb0e2af4a0f571457.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">The Automation Paradox</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../report/report.html" aria-current="page"> 
<span class="menu-text">Report</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/tyakovenko/ai-job-market"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">Executive Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a>
  <ul class="collapse">
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a></li>
  </ul></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">2. Data Sources</a></li>
  <li><a href="#automation-risk-distribution" id="toc-automation-risk-distribution" class="nav-link" data-scroll-target="#automation-risk-distribution">3. Automation Risk Distribution</a></li>
  <li><a href="#the-core-relationship-automation-risk-vs.-job-growth" id="toc-the-core-relationship-automation-risk-vs.-job-growth" class="nav-link" data-scroll-target="#the-core-relationship-automation-risk-vs.-job-growth">4. The Core Relationship: Automation Risk vs.&nbsp;Job Growth</a></li>
  <li><a href="#who-is-most-at-risk" id="toc-who-is-most-at-risk" class="nav-link" data-scroll-target="#who-is-most-at-risk">5. Who Is Most At Risk?</a></li>
  <li><a href="#who-is-safe" id="toc-who-is-safe" class="nav-link" data-scroll-target="#who-is-safe">6. Who Is Safe?</a></li>
  <li><a href="#the-economic-divide" id="toc-the-economic-divide" class="nav-link" data-scroll-target="#the-economic-divide">7. The Economic Divide</a></li>
  <li><a href="#cluster-analysis-three-paths-forward" id="toc-cluster-analysis-three-paths-forward" class="nav-link" data-scroll-target="#cluster-analysis-three-paths-forward">8. Cluster Analysis: Three Paths Forward</a></li>
  <li><a href="#then-vs.-now-the-genai-risk-shift-2013-2025" id="toc-then-vs.-now-the-genai-risk-shift-2013-2025" class="nav-link" data-scroll-target="#then-vs.-now-the-genai-risk-shift-2013-2025">9. Then vs.&nbsp;Now: The GenAI Risk Shift (2013 → 2025)</a>
  <ul class="collapse">
  <li><a href="#the-sector-level-flip" id="toc-the-sector-level-flip" class="nav-link" data-scroll-target="#the-sector-level-flip">The Sector-Level Flip</a></li>
  <li><a href="#the-occupation-level-picture" id="toc-the-occupation-level-picture" class="nav-link" data-scroll-target="#the-occupation-level-picture">The Occupation-Level Picture</a></li>
  <li><a href="#what-this-means" id="toc-what-this-means" class="nav-link" data-scroll-target="#what-this-means">What This Means</a></li>
  </ul></li>
  <li><a href="#conclusions-and-policy-implications" id="toc-conclusions-and-policy-implications" class="nav-link" data-scroll-target="#conclusions-and-policy-implications">10. Conclusions and Policy Implications</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Automation Paradox: Who Really Gets Hurt When AI Takes Over?</h1>
<p class="subtitle lead">AI’s Impact on the Job Market</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Taya Yakovenko </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="executive-summary" class="level2">
<h2 class="anchored" data-anchor-id="executive-summary">Executive Summary</h2>
<p>This report analyzes AI’s effect on the US labor market using three datasets: Frey &amp; Osborne’s automation probability scores (2013), BLS 2024–2034 employment projections, and the ILO’s 2025 Generative AI Occupational Exposure Index.</p>
<p>The <strong>Automation Paradox</strong>: most workers exposed to AI are currently seeing stable or growing employment. Yet hidden inside that aggregate is a concentrated crisis. <strong>144</strong> occupations (24% of analyzed jobs) combine high automation risk with low wages and low education which leaves workers with no economic safety net. These are the jobs where displacement is not a future concern but a present reality.</p>
<p><strong>Key findings:</strong></p>
<ul>
<li><strong>283</strong> of 606 matched occupations carry high (≥70%) automation risk — primarily in Office &amp; Admin Support, Production, and Food Preparation</li>
<li>High-risk occupations have a median wage of <strong>$48,350</strong> — compared to <strong>$79,000</strong> for low-risk occupations</li>
<li>A linear regression confirms automation risk negatively predicts employment growth (coefficient: −4.15), but the full model (automation + wage + education + occupation group) explains only R² = 0.175 of variance on the test set — automation is predictive but not deterministic</li>
<li>The most important protective factor is <strong>education + wage combined</strong> (adaptive capacity score), not automation risk alone</li>
<li>A “Then vs.&nbsp;Now” comparison using the ILO 2025 GenAI Exposure Index reveals the risk map has fundamentally shifted: <strong>Computer &amp; Math</strong> reversed from low traditional risk (13%) to highest GenAI exposure (56%), while <strong>Production and Construction</strong> — flagged as near-certain automation targets in 2013 — score among the lowest on GenAI exposure today.</li>
</ul>
<hr>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>Aggregate employment statistics look healthy but averages hide the key distribution. This report investigates which occupations are genuinely at risk, what makes some workers resilient and others vulnerable, and where the US labor market is heading through 2034.</p>
<section id="research-questions" class="level3">
<h3 class="anchored" data-anchor-id="research-questions">Research Questions</h3>
<ol type="1">
<li>Which occupations face the highest automation risk, and are those the same occupations projected to decline?</li>
<li>Does automation risk alone predict employment change, or do other factors matter more?</li>
<li>Can we identify a “vulnerability cluster” — occupations combining high automation exposure with low adaptive capacity?</li>
</ol>
<hr>
</section>
</section>
<section id="data-sources" class="level2">
<h2 class="anchored" data-anchor-id="data-sources">2. Data Sources</h2>
<p><strong>A note on the original dataset:</strong> This project was initially scoped around the <em>AI Impact on Job Market</em> dataset on Kaggle. Preliminary analysis showed near-zero correlations between all variables (r ≈ 0.001–0.012 across every pair), which is a hallmark of randomly generated synthetic data — there is no real signal to analyze. That dataset was set aside in favor of the three real-world sources described below.</p>
<p>Three datasets are combined for this analysis:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Dataset</th>
<th>Source</th>
<th>Coverage</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Automation Probability Scores</td>
<td>Frey &amp; Osborne (2013), <em>The Future of Employment</em></td>
<td>702 US occupations</td>
<td>Traditional automation baseline (“then”)</td>
</tr>
<tr class="even">
<td>Employment Projections 2024–2034</td>
<td>US Bureau of Labor Statistics</td>
<td>832 occupations</td>
<td>Employment outlook</td>
</tr>
<tr class="odd">
<td>GenAI Occupational Exposure Index</td>
<td>Gmyrek et al.&nbsp;(2025), ILO Working Paper 140</td>
<td>427 ISCO-08 occupations</td>
<td>GenAI exposure (“now”)</td>
</tr>
<tr class="even">
<td><strong>Analysis dataset</strong></td>
<td>Inner join F&amp;O × BLS; left join ILO via crosswalk</td>
<td></td>
<td><strong>606 occupations, 99% with GenAI scores</strong></td>
</tr>
</tbody>
</table>
<p>Frey &amp; Osborne and BLS are joined on SOC codes (86% match rate). The ILO dataset uses ISCO-08 codes and is bridged via the BLS official ISCO-08 × SOC crosswalk, covering 600 of 606 occupations.</p>
<hr>
</section>
<section id="automation-risk-distribution" class="level2">
<h2 class="anchored" data-anchor-id="automation-risk-distribution">3. Automation Risk Distribution</h2>
<div id="7adf2ab4" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-3-output-1.png" width="652" height="364" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The distribution is bimodal: most occupations cluster at the extremes rather than the middle. Work tasks tend to be either primarily routine (highly automatable) or primarily non-routine (resistant to automation), with few genuinely ambiguous cases.</p>
<p><strong>By occupation group</strong>, the highest-risk sectors are Office &amp; Administrative Support (84% average probability), Production (82%), Farming &amp; Fishing (78%), and Building &amp; Grounds (78%). The safest sectors are Community &amp; Social Service (5%), Healthcare Practitioners (12%), Computer &amp; Math (13%), and Management (14%).</p>
<div id="8a4dea92" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-4-output-1.png" width="845" height="556" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="the-core-relationship-automation-risk-vs.-job-growth" class="level2">
<h2 class="anchored" data-anchor-id="the-core-relationship-automation-risk-vs.-job-growth">4. The Core Relationship: Automation Risk vs.&nbsp;Job Growth</h2>
<div id="102913bb" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-5-output-1.png" width="844" height="460" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The scatter plot reveals the Automation Paradox visually. There is a clear negative trend — occupations with higher automation probability cluster toward the lower portion of the chart. But the relationship is wide and noisy. Many high-automation occupations still show positive projected employment growth. Automation risk is <em>predictive</em> but not <em>deterministic</em>.</p>
<p><strong>Correlation:</strong> r = −0.414 between <code>automation_prob</code> and <code>emp_change_pct</code>. Moderate negative relationship. <strong>Full model R² = 0.175 (test set)</strong> — even with automation risk, wage, education, and 21 occupation-group controls, the model explains only 17.5% of variance in employment change. This is the core empirical evidence for the Automation Paradox: most of what determines a job’s employment trajectory lies outside AI exposure.</p>
<hr>
</section>
<section id="who-is-most-at-risk" class="level2">
<h2 class="anchored" data-anchor-id="who-is-most-at-risk">5. Who Is Most At Risk?</h2>
<div id="24c1e52b" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-6-output-1.png" width="1024" height="459" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The most at-risk occupations combine high automation probability (≥70%) with the steepest projected employment declines: word processors and typists (−36%), telephone operators (−28%), data entry keyers (−26%), telemarketers (−22%), and payroll clerks (−17%). These are not hypothetical future risks — BLS projects active job losses in all of them through 2034.</p>
<hr>
</section>
<section id="who-is-safe" class="level2">
<h2 class="anchored" data-anchor-id="who-is-safe">6. Who Is Safe?</h2>
<div id="7686d59b" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-7-output-1.png" width="955" height="460" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The safest and fastest-growing occupations are concentrated in healthcare (nurse practitioners, physician assistants, home health aides) and technology (software developers, data scientists). These roles require complex human judgment, physical dexterity, deep domain expertise, or meaningful human interaction — all barriers to automation.</p>
<hr>
</section>
<section id="the-economic-divide" class="level2">
<h2 class="anchored" data-anchor-id="the-economic-divide">7. The Economic Divide</h2>
<div id="2296361f" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-8-output-1.png" width="1013" height="365" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>High-risk occupations have a median annual wage of <strong>$48,350</strong>, compared to <strong>$79,000</strong> for low-risk occupations — a <strong>$30,650</strong> gap.</p>
<p>The box plot makes the distributional difference even clearer. Vulnerable occupations (high automation + low adaptive capacity) have a tightly compressed wage range centered at <strong>$40,260</strong>. Non-vulnerable occupations have a median of <strong>$63,280</strong> with a wide spread extending into six figures. The workers most threatened by AI are also the least able to afford the retraining, relocation, or career transition that adaptation requires.</p>
<hr>
</section>
<section id="cluster-analysis-three-paths-forward" class="level2">
<h2 class="anchored" data-anchor-id="cluster-analysis-three-paths-forward">8. Cluster Analysis: Three Paths Forward</h2>
<p>K-Means clustering reveals three occupational trajectories (elbow analysis suggested k=4, but k=3 produced fully interpretable segments with no loss of structure):</p>
<div id="60e37c42" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-9-output-1.png" width="928" height="365" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="c85a512c" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Size</th>
<th data-quarto-table-cell-role="th">Avg Automation Prob</th>
<th data-quarto-table-cell-role="th">Avg Adaptive Capacity</th>
<th data-quarto-table-cell-role="th">Avg Emp Change %</th>
<th data-quarto-table-cell-role="th">Avg Wage</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">cluster_label</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">High Risk / Low Resilience</th>
<td>305 (50.8%)</td>
<td>85.0%</td>
<td>0.11</td>
<td>-1.75%</td>
<td>$49,287</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Low Risk / Stable</th>
<td>225 (37.5%)</td>
<td>27.0%</td>
<td>0.32</td>
<td>+3.06%</td>
<td>$66,965</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Low Risk / High Skill</th>
<td>70 (11.7%)</td>
<td>9.0%</td>
<td>0.62</td>
<td>+5.51%</td>
<td>$126,322</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The “High Risk / Low Resilience” cluster (50% of matched occupations) faces declining employment with virtually no adaptive buffer. The “Low Risk / High Skill” cluster (12% of occupations) has near-zero automation risk, strong job growth, and wages 2.5× higher than the at-risk group.</p>
<hr>
</section>
<section id="then-vs.-now-the-genai-risk-shift-2013-2025" class="level2">
<h2 class="anchored" data-anchor-id="then-vs.-now-the-genai-risk-shift-2013-2025">9. Then vs.&nbsp;Now: The GenAI Risk Shift (2013 → 2025)</h2>
<p>Frey &amp; Osborne (2013) measured automation risk for routine, algorithmic tasks. Generative AI targets different work: language, reasoning, and information synthesis. The ILO’s 2025 GenAI Occupational Exposure Index (Gmyrek et al., ILO Working Paper 140) quantifies that new risk across 29,753 tasks in 427 ISCO-08 occupations.</p>
<p>If the risk landscape has shifted since 2013, policies and career advice built on those assumptions may be protecting the wrong workers.</p>
<section id="the-sector-level-flip" class="level3">
<h3 class="anchored" data-anchor-id="the-sector-level-flip">The Sector-Level Flip</h3>
<div id="dab4e9fc" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-12-output-1.png" width="919" height="748" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Lines pointing <strong>right</strong> mark sectors where GenAI exposure <em>rose</em> from 2013 — knowledge and information work that language models target directly. Lines pointing <strong>left</strong> are physical sectors where GenAI has no displacement mechanism.</p>
</section>
<section id="the-occupation-level-picture" class="level3">
<h3 class="anchored" data-anchor-id="the-occupation-level-picture">The Occupation-Level Picture</h3>
<div id="1bc7d418" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/cell-13-output-1.png" width="844" height="460" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Points <strong>above</strong> the diagonal face more GenAI exposure than 2013 models predicted. Points <strong>below</strong> had high traditional automation risk that GenAI does not replicate.</p>
<p><strong>The five most newly exposed occupations</strong> (largest positive delta):</p>
<div id="cf287557" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="13">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 52%">
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Occupation</th>
<th style="text-align: left;">Sector</th>
<th style="text-align: left;">2013 Risk</th>
<th style="text-align: left;">GenAI 2025</th>
<th style="text-align: right;">Δ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Credit counselors</td>
<td style="text-align: left;">Business &amp; Financial</td>
<td style="text-align: left;">4%</td>
<td style="text-align: left;">60%</td>
<td style="text-align: right;">0.56</td>
</tr>
<tr class="even">
<td style="text-align: left;">Operations research analysts</td>
<td style="text-align: left;">Computer &amp; Math</td>
<td style="text-align: left;">4%</td>
<td style="text-align: left;">56%</td>
<td style="text-align: right;">0.53</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Securities, commodities, and financial services sales agents</td>
<td style="text-align: left;">Sales</td>
<td style="text-align: left;">2%</td>
<td style="text-align: left;">54%</td>
<td style="text-align: right;">0.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mathematicians</td>
<td style="text-align: left;">Computer &amp; Math</td>
<td style="text-align: left;">5%</td>
<td style="text-align: left;">56%</td>
<td style="text-align: right;">0.51</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Writers and authors</td>
<td style="text-align: left;">Arts &amp; Media</td>
<td style="text-align: left;">4%</td>
<td style="text-align: left;">55%</td>
<td style="text-align: right;">0.51</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>The five most de-risked occupations</strong> (largest negative delta):</p>
<div id="b7d46af9" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="14">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 51%">
<col style="width: 21%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Occupation</th>
<th style="text-align: left;">Sector</th>
<th style="text-align: left;">2013 Risk</th>
<th style="text-align: left;">GenAI 2025</th>
<th style="text-align: right;">Δ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sewers, hand</td>
<td style="text-align: left;">Production</td>
<td style="text-align: left;">99%</td>
<td style="text-align: left;">12%</td>
<td style="text-align: right;">-0.87</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log graders and scalers</td>
<td style="text-align: left;">Farming &amp; Fishing</td>
<td style="text-align: left;">97%</td>
<td style="text-align: left;">12%</td>
<td style="text-align: right;">-0.85</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Helpers–painters, paperhangers, plasterers, and stucco masons</td>
<td style="text-align: left;">Construction &amp; Extraction</td>
<td style="text-align: left;">94%</td>
<td style="text-align: left;">9%</td>
<td style="text-align: right;">-0.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pesticide handlers, sprayers, and applicators, vegetation</td>
<td style="text-align: left;">Building &amp; Grounds</td>
<td style="text-align: left;">97%</td>
<td style="text-align: left;">13%</td>
<td style="text-align: right;">-0.84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cement masons and concrete finishers</td>
<td style="text-align: left;">Construction &amp; Extraction</td>
<td style="text-align: left;">94%</td>
<td style="text-align: left;">10%</td>
<td style="text-align: right;">-0.84</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="what-this-means" class="level3">
<h3 class="anchored" data-anchor-id="what-this-means">What This Means</h3>
<p>Both eras agree on one point: <strong>Office &amp; Administrative Support is highly exposed</strong> (84% traditional, 52% GenAI). Beyond that, the risk maps diverge.</p>
<p>GenAI targets <strong>language, reasoning, and information synthesis</strong>, not physical manipulation. Writers, analysts, counselors, and mathematicians appear in the newly-exposed list; brickmasons, sewers, and groundskeepers appear in the de-risked list. The physical dexterity barrier that protected manual workers from robotics also protects them from GenAI.</p>
<p><strong>Retraining programs built on 2013 risk maps may be pointing workers toward newly-exposed roles.</strong> Healthcare and skilled trades remain lower-risk options from a GenAI standpoint, even as physical automation continues to advance.</p>
<hr>
</section>
</section>
<section id="conclusions-and-policy-implications" class="level2">
<h2 class="anchored" data-anchor-id="conclusions-and-policy-implications">10. Conclusions and Policy Implications</h2>
<p>Automation risk and employment decline are related (r = −0.414) but not synonymous. Many high-automation occupations still show positive growth projections because AI raises productivity and creates new roles even as it displaces specific tasks.</p>
<p>That aggregate picture obscures a more concentrated problem. <strong>144</strong> occupations (23.8%) combine high automation exposure with wages and education too low to support adaptation. These workers absorb displacement costs with limited ability to transition.</p>
<p><strong>Implications:</strong> 1. <strong>Targeted retraining, not general retraining.</strong> The vulnerable population is identifiable by occupation — Office &amp; Admin Support, Production, Food Preparation. Broadly available training programs miss the specific workers at risk. 2. <strong>Wage floors and education must rise together.</strong> Low-wage workers cannot access training, relocation, or extended job search even with higher education. Neither lever works alone — income support during transition is as necessary as the training itself. 3. <strong>Healthcare investment is a hedge.</strong> The fastest-growing, safest occupations are concentrated in healthcare — a sector driven by demographics, not AI adoption. Policies that reduce barriers to healthcare careers (licensing, cost, geographic access) are simultaneously labor market policies.</p>
<p><strong>Limitations:</strong> Frey &amp; Osborne’s scores date to 2013 and reflect a pre-GenAI understanding of automation risk — which is why this report includes the ILO 2025 comparison in Section 9. Even so, the ILO scores are global (ISCO-08) and were validated using Polish worker surveys; US-specific GenAI adoption rates may differ. BLS projections are point estimates with unquantified uncertainty. The merged dataset covers 606 of 832 BLS-tracked occupations; 6 occupations have no ISCO-08 equivalent and are excluded from the then/now analysis only.</p>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Frey, C.B. &amp; Osborne, M.A.&nbsp;(2013). <em>The Future of Employment: How Susceptible Are Jobs to Computerisation?</em> Oxford Martin School Working Paper.</li>
<li>U.S. Bureau of Labor Statistics (2024). <em>Employment Projections 2024–2034.</em> U.S. Department of Labor. https://www.bls.gov/emp/</li>
<li>Gmyrek, P., Berg, J., &amp; Bescond, D. (2025). <em>Generative AI and Jobs: A Refined Global Index of Occupational Exposure.</em> ILO Working Paper 140. International Labour Organization. https://www.ilo.org/publications/generative-ai-and-jobs-refined-global-index-occupational-exposure</li>
<li>Acemoglu, D. &amp; Restrepo, P. (2018). Artificial Intelligence, Automation, and Work. <em>NBER Working Paper 24196.</em></li>
<li>Broady, K., McGrew, C., &amp; Ouyang, A. (2024). <em>Measuring US Workers’ Capacity to Adapt to AI-Driven Job Displacement.</em> The Brookings Institution.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>